[package]
name = "makopa-kernel"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
build = "build.rs"

[dependencies]
makopa-address-space.workspace = true
makopa-boot-contract.workspace = true
makopa-frame-allocator.workspace = true
x86_64.workspace = true

[[bin]]
name = "makopa-kernel"
path = "src/main.rs"
test = false
bench = false
